platform :ios, '15.4'

require_relative '../node_modules/react-native/scripts/react_native_pods.rb'
ENV['RCT_NEW_ARCH_ENABLED'] ||= '0'
prepare_react_native_project!

target 'DocScanPro' do
  config = use_native_modules!

  use_react_native!(
    path: config[:reactNativePath],
    hermes_enabled: true,
    fabric_enabled: true
  )

  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath], mac_catalyst_enabled: false)
    # Force iOS 15.4 across all targets to silence min-version warnings
    (installer.pods_project.targets + installer.aggregate_targets.flat_map { |a| a.user_project.native_targets }).uniq.each do |t|
      t.build_configurations.each { |cfg| cfg.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.4' }
    end
  end
end
