name: CI

on: [push, pull_request]

jobs:
  checks:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - run: pnpm i --frozen-lockfile
      - run: pnpm lint
      - run: pnpm typecheck


