name: CI

on: [push, pull_request]

jobs:
  checks:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack & activate pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.0.0 --activate
          pnpm -v

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck